---Borrado de Tablas
DROP TABLE DDS_F5.propuesta;
DROP TABLE DDS_F5.infraccion;
DROP TABLE DDS_F5.equipo_jugador;
DROP TABLE DDS_F5.amigo;
DROP TABLE DDS_F5.calificacion;
DROP TABLE DDS_F5.inscripcion;
DROP TABLE DDS_F5.Partido;
DROP TABLE DDS_F5.jugador;
DROP TABLE DDS_F5.Administrador;
DROP TABLE DDS_F5.equipo;
DROP TABLE DDS_F5.tipo_inscripcion;